/**
 * 
 */
package dream.examples.tasks;

import javax.swing.JFrame;

/**
 *
 * @author kamathar
 */
public class WorkerProcess implements UiUpdatesListner {
	private javax.swing.JFrame mainFrame;
	private javax.swing.JPanel DisplayPanel;
	private javax.swing.JTextArea infoTextArea;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JLabel infoLabel;
	WorkerHelper manager;

	/**
	 * Creates new form WorkerProcess
	 */
	public WorkerProcess(WorkerHelper manager2) {
		this.manager = manager2;
		this.manager.addListners(this);
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {
		mainFrame = new JFrame("Distributed Task Management");
		mainFrame.setResizable(true);
		mainFrame.setSize(300, 100);
		DisplayPanel = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		infoTextArea = new javax.swing.JTextArea();

		infoLabel = new javax.swing.JLabel();

		mainFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		infoTextArea.setEditable(false);
		infoTextArea.setColumns(100);
		infoTextArea.setRows(20);
		jScrollPane1.setViewportView(infoTextArea);

		javax.swing.GroupLayout DisplayPanelLayout = new javax.swing.GroupLayout(DisplayPanel);
		DisplayPanel.setLayout(DisplayPanelLayout);
		DisplayPanelLayout
				.setHorizontalGroup(DisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(DisplayPanelLayout.createSequentialGroup().addContainerGap()
								.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
								.addContainerGap()));
		DisplayPanelLayout.setVerticalGroup(DisplayPanelLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(DisplayPanelLayout
						.createSequentialGroup().addGap(0, 0, 0).addComponent(jScrollPane1).addContainerGap()));

		infoLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
		infoLabel.setText("Task List");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(mainFrame.getContentPane());
		mainFrame.getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap()
						.addComponent(DisplayPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18).addGap(25, 25, 25))
				.addGroup(layout.createSequentialGroup().addGap(24, 24, 24)
						.addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(infoLabel).addGap(3, 3, 3)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
								DisplayPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));

		mainFrame.setVisible(true);
		mainFrame.pack();
	}

	void initUi() {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(WorkerProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(WorkerProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(WorkerProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(WorkerProcess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}

	}

	@Override
	public void updateTasks(String task) {
		infoTextArea.append("\n" + task);
		infoTextArea.append("\n**************************************************************");
		mainFrame.repaint();
		mainFrame.revalidate();
	}

	public static void main(String args[]) {
		WorkerHelper manager = new WorkerHelper();
		WorkerProcess snapshotUi = new WorkerProcess(manager);
		snapshotUi.initUi();
		Thread S = new Thread(manager);
		S.start();
	}
}